name: Manual Run

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Enter environment"
        required: true
        default: staging

jobs:
  manual-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Input
        run: echo "Environment ${{ github.event.inputs.environment }}"